import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/sections/navbar/Navbar";
import ModalContextProvider from "@/context/modal/ModalContextProvider";
import ThemeModal from "@/theme/ThemeModal";
import ThemeMenu from "@/sections/theme-modal-menu/ThemeMenu";
import ThemeContextProvider from "@/context/theme/ThemeContextProvider";
import dynamic from "next/dynamic";
const Main = dynamic(() => import("../components/main/Main"), { ssr: false} )

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeContextProvider>
      <ModalContextProvider>
        <body>          
          <div>          
          <Main>
          <Navbar />
          { children }
          <ThemeMenu />
          <ThemeModal />
          </Main>
          </div>
          
        </body>
      </ModalContextProvider>
      </ThemeContextProvider>
    </html>
  );
}
